export const countries = [
  { value: 'MY', label: 'Malaysia', flag: '🇲🇾' },
  { value: 'SG', label: 'Singapore', flag: '🇸🇬' },
  { value: 'US', label: 'United States', flag: '🇺🇸' },
  { value: 'UK', label: 'United Kingdom', flag: '🇬🇧' },
  { value: 'AU', label: 'Australia', flag: '🇦🇺' },
  { value: 'CA', label: 'Canada', flag: '🇨🇦' },
  { value: 'IN', label: 'India', flag: '🇮🇳' },
  { value: 'CN', label: 'China', flag: '🇨🇳' },
  { value: 'JP', label: 'Japan', flag: '🇯🇵' },
  { value: 'KR', label: 'South Korea', flag: '🇰🇷' },
  { value: 'TH', label: 'Thailand', flag: '🇹🇭' },
  { value: 'ID', label: 'Indonesia', flag: '🇮🇩' },
  { value: 'PH', label: 'Philippines', flag: '🇵🇭' },
  { value: 'VN', label: 'Vietnam', flag: '🇻🇳' },
  { value: 'NZ', label: 'New Zealand', flag: '🇳🇿' },
  { value: 'FR', label: 'France', flag: '🇫🇷' },
  { value: 'DE', label: 'Germany', flag: '🇩🇪' },
  { value: 'IT', label: 'Italy', flag: '🇮🇹' },
  { value: 'ES', label: 'Spain', flag: '🇪🇸' },
  { value: 'NL', label: 'Netherlands', flag: '🇳🇱' },
  { value: 'SE', label: 'Sweden', flag: '🇸🇪' },
  { value: 'NO', label: 'Norway', flag: '🇳🇴' },
  { value: 'DK', label: 'Denmark', flag: '🇩🇰' },
  { value: 'FI', label: 'Finland', flag: '🇫🇮' },
  { value: 'BR', label: 'Brazil', flag: '🇧🇷' },
  { value: 'MX', label: 'Mexico', flag: '🇲🇽' },
  { value: 'AR', label: 'Argentina', flag: '🇦🇷' },
  { value: 'ZA', label: 'South Africa', flag: '🇿🇦' },
  { value: 'EG', label: 'Egypt', flag: '🇪🇬' },
  { value: 'NG', label: 'Nigeria', flag: '🇳🇬' },
  { value: 'KE', label: 'Kenya', flag: '🇰🇪' },
  { value: 'AE', label: 'United Arab Emirates', flag: '🇦🇪' },
  { value: 'SA', label: 'Saudi Arabia', flag: '🇸🇦' },
  { value: 'PK', label: 'Pakistan', flag: '🇵🇰' },
  { value: 'BD', label: 'Bangladesh', flag: '🇧🇩' },
  { value: 'LK', label: 'Sri Lanka', flag: '🇱🇰' },
  { value: 'NP', label: 'Nepal', flag: '🇳🇵' },
  { value: 'HK', label: 'Hong Kong', flag: '🇭🇰' },
  { value: 'TW', label: 'Taiwan', flag: '🇹🇼' },
];